### PR TITLE
Make responsive

### PR DESCRIPTION
**Pull request by MatthewElson**
collective.html and css made responsive

### CODE REVIEW

**Review by MatthewElson — COMMENTED** [review]
For commit a862e2c I committed the wrong folder, so the css is missing. See the next commit.

**Comment by MatthewElson** [comment]
So I've more or less finished the home_newversion.html unfortunately I've having some troubles in the mobile view where some elements won't go full width. Perhaps somebody could fix that.

**Comment by MatthewElson** [comment]
the log1.html file was a little harder to make responsive. Check it out, if necessary we'll discuss it and change it.

**Comment by MatthewElson** [comment]
Ok, that's all the pages. I didn't do the quiz.css page as the css file her on github said "changed login design and made responsive" so I presume it's done. If not, let me know and I can do that too.

**Comment by apuayush** [comment]
yeaa sure .. if you want to change that also i have know problem... thank you. btw sorry for replying so late i was stuck up in some work so couldnt continue github for these many days.

**Pull request merged**
